# Generated by Django 5.1.1 on 2024-10-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
