# Generated by Django 5.1.1 on 2024-10-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_classroom_name_subject_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
