# Generated by Django 5.1.1 on 2024-10-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_alter_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(default='D1 анги', max_length=100),
        ),
    ]
