# Generated by Django 5.1.1 on 2024-10-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_alter_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
