# Generated by Django 5.1.1 on 2024-10-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_schedule_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='schedule_app.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Availability',
                'verbose_name_plural': 'Teacher Availabilities',
                'ordering': ['start_date'],
            },
        ),
    ]
