# Generated by Django 5.1.1 on 2024-10-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0008_grade_teacher_busy_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='busy_days',
            field=models.JSONField(default=list),
        ),
    ]
