# Generated by Django 5.1.1 on 2024-10-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0009_alter_teacher_busy_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='busy_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
