# Generated by Django 5.1.1 on 2024-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0010_alter_teacher_busy_days_alter_teacher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='TeacherAvailability',
            new_name='TeacherAvailabeDates',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='busy_days',
            new_name='busy_periods',
        ),
    ]
