# Generated by Django 5.1.1 on 2024-10-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0011_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.CharField(default='08:40', max_length=10),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.CharField(default='08:00', max_length=10),
        ),
    ]
