# Generated by Django 5.1.1 on 2024-10-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0013_remove_schedule_end_time_remove_schedule_start_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherAvailabeDates',
            new_name='TeacherAvailableDates',
        ),
    ]
