# Generated by Django 5.1.1 on 2024-10-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0014_rename_teacheravailabedates_teacheravailabledates'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='remaining_hours',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_hours',
            field=models.IntegerField(default=33),
        ),
    ]
